import { Separator } from "@/components/ui/separator";
import "./globals.css";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import Link from "next/link";
import ContactDialog from "@/components/ContactDialog";
import { Toaster } from "@/components/ui/toaster";

const quicksand = Quicksand({ weight: ["500"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={quicksand.className}>
        <section className="flex flex-col">
          <div className="flex items-center max-sm:justify-between py-4 px-2 sm:gap-6 lg:py-6 lg:px-4 text-lg lg:text-2xl font-normal lg:font-medium">
            <Link href="/" className="cursor-pointer">
              About Me
            </Link>
            <Link href="/projects" className="curssor-pointer">
              Projects
            </Link>
            {/* <h1 className="cursor-pointer">Contact Me</h1> */}
            <ContactDialog />
          </div>
          <Separator className="h-0.5 bg-[#404F4C]" />
        </section>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
